program: experiments.sweep_experiment
method: random
project: ResNet18Optimizing
entity: kn-bmi
metric:
  goal: minimize
  name: val_loss
parameters:
  optimizer:
    values: ['adam', 'adamax','adamw', 'nadam', 'radam', 'rmsprop']

  learning_rate:
    values: [1, 1e-1, 1e-2, 1e-3, 1e-4, 3e-4, 3e-3, 3e-2, 3e-1]

  beta:
    values: [0.999, 0.99, 0.97, 0.95]

  weight_decay:
    values: [1e-4, 1e-5, 1e-6, 0]

  amsgrad:
    values: [True, False]

  batch_size:
    values: [16, 32, 64]

  weight_0:
    distribution: normal
    mu: 1
    sigma: 0.1

  weight_1:
    distribution: normal
    mu: 1.5
    sigma: 0.2

  weight_2:
    distribution: normal
    mu: 2.65
    sigma: 0.28

  weight_3:
    distribution: normal
    mu: 2
    sigma: 0.21

command:
  - ${env}
  - PL_TORCH_DISTRIBUTED_BACKEND=gloo poetry run python3 -m
  - ${program}
  - ${args}
